server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,configprops,env
  endpoint:
    health:
      show-details: always
      show-components: always

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.notirail: ${APP_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
