spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}

grpc:
  server:
    host: ${GRPC_HOST:localhost}
    port: ${GRPC_PORT:9090}
    maximum-message-size: 4194304 # in bytes (4MB)

redis:
  credential-ttl: 60s
  event-idempotency-ttl: 7d
  revoked-marker-ttl: 30d
