spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

grpc:
  server:
    host: ${GRPC_HOST}
    port: ${GRPC_PORT:9090}
    maximum-message-size: ${GRPC_MAXIMUM_MESSAGE_SIZE:4194304} # in bytes (4MB)

redis:
  credential-ttl: ${REDIS_CREDENTIAL_TTL:60s}
  event-idempotency-ttl: ${REDIS_EVENT_IDEMPOTENCY_TTL:7d}
  revoked-marker-ttl: ${REDIS_REVOKED_MARKER_TTL:30d}
